const express = require('express')
const { userRouter } = require('./user')
const { courseRouter } = require('./course')
const { classRouter } = require('./class')
const { enrollmentRouter } = require('./enrollment')
const { testRouter } = require('./test')
const { default: noteRouter } = require('./note')
const { default: scoreRouter } = require('./score')
const { default: majorRouter } = require('./major')
const { default: deadlineRouter } = require('./deadline')
const { default: notiRouter } = require('./noti')

const Router = express.Router()

Router.get('/', (req, res) => res.json('ready to use'))

Router.use('/user', userRouter )
Router.use('/course', courseRouter)
Router.use('/class', classRouter)
Router.use('/enrollment', enrollmentRouter)
Router.use('/test', testRouter)
Router.use('/note', noteRouter)
Router.use('/score', scoreRouter)
Router.use('/major', majorRouter)
Router.use('/deadline', deadlineRouter)
Router.use('/noti', notiRouter)
module.exports = { Router }